apiVersion: apps/v1
kind: Deployment
metadata:
  name: text2emoji-app
  namespace: iykra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: text2emoji-app
  template:
    metadata:
      labels:
        app: text2emoji-app
    spec:
      containers:
      - name: text2emoji-app
        image: us-central1-docker.pkg.dev/iykra-aef2/iykra/text2emoji:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "2"
            memory: "4Gi"
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 60
          periodSeconds: 15